# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel multimedia device drivers.
#

# Please keep it alphabetically sorted by Kconfig name
# (e. g. LC_ALL=C sort Makefile)


obj-$(CONFIG_SAA716X_CORE) += saa716x/
#obj-$(CONFIG_TBS_PCIE_CAP) += tbscapture/
#obj-$(CONFIG_TBS_PCIE2_CAP) += tbscapture2/
#obj-$(CONFIG_TBS_PCIE_CI) += tbsci/
#obj-$(CONFIG_DVB_TBSECP3) += tbsecp3/
#obj-$(CONFIG_TBS_PCIE_MOD) += tbsmod/
