# SPDX-License-Identifier: GPL-2.0
#
# Makefile for common V4L/DVB tuners
#

ccflags-y += -I$(M)/frontends


# Please keep it alphabetically sorted by Kconfig name
# (e. g. LC_ALL=C sort Makefile)
obj-$(CONFIG_MEDIA_TUNER_SI2157) += si2157.o

